version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-sam-playground-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1pvp4db67xsa0"
s3_prefix = "aws-sam-playground-app"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
