name: Teardown

on:
  pull_request:
    types: [ closed ]

jobs:
  teardown-preview:
    name: Teardown
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Teardown
      continue-on-error: true
      run: |
        aws cloudformation delete-stack --stack-name pull-request-${{ github.event.number }}
